spring:
 application:
   name: employee-management-system
 datasource:
   url: jdbc:mysql://localhost:3306/employee_mnc?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
   username: root
   password: root@39
   driver-class-name: com.mysql.cj.jdbc.Driver
 jpa:
   hibernate:
     ddl-auto: update
   show-sql: true
   properties:
     hibernate:
       dialect: org.hibernate.dialect.MySQL8Dialect
       format_sql: true
 security:
   user:
     name: admin
     password: admin123
server:
 port: 8086
management:
 endpoints:
   web:
     exposure:
       include: health,info,metrics
logging:
 level:
   com.mnc: DEBUG
   org.springframework.security: DEBUG

